name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    environment:
      name: continuous-integration
    steps:
      # Need some depth to figure out what changed from previous commit (e.g. version.json)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build and Unit Test
        run: ./gradlew test jar
      - name: Upload to Bintray
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_GPG_PASSPHRASE: ${{ secrets.BINTRAY_GPG_PASSPHRASE }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./release-ci.sh
      - name: Tag Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./release-tag.sh
      - name: Upload to Maven Central
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_GPG_PASSPHRASE: ${{ secrets.BINTRAY_GPG_PASSPHRASE }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./release-maven-central.sh

